### ISSUE TITLE
Crash on first room down. 

### ISSUE THREAD

**Issue by brose7561** [UQcsse3200/2024-studio-1#551]
## How To Reproduce
Steps to reproduce the behaviour:
kill all the animals
walk down to room two
kill the small animals 
bug starts the first time minator is hit.
minator is then hit by non shown projectiles  out of shotgun range
the game crashes after killing minator. 

logs: 

INFO: Creating collectible with specification: buff:energydrink:medium 
    12:14:24:221 com.csse3200.game.entities.factories.CollectibleFactory create 
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.badlogic.gdx.graphics.Texture.getHeight()" because "this.texture" is null
	at com.csse3200.game.rendering.TextureRenderComponent.scaleEntity(TextureRenderComponent.java:27)
	at com.csse3200.game.entities.factories.CollectibleFactory.createCollectibleEntity(CollectibleFactory.java:88)
	at com.csse3200.game.entities.factories.CollectibleFactory.createCollectibleEntity(CollectibleFactory.java:100)
	at com.csse3200.game.areas.BaseRoom.spawnItem(BaseRoom.java:304)
	at com.csse3200.game.areas.EnemyRoom.spawnItem(EnemyRoom.java:168)
	at com.csse3200.game.areas.EnemyRoom.spawnItems(EnemyRoom.java:199)
	at com.csse3200.game.areas.EnemyRoom$1.run(EnemyRoom.java:102)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:208)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.csse3200.game.desktop.DesktopLauncher.main(DesktopLauncher.java:10)

## Expected Behaviour
not hit out of shotgun range
not crash. 

## Temporary Fix
don't go down to room two

**Comment by vsinh14** [comment]
Item team is fixing this
